% memorydisp displays the number of bytes that the current variables in the
% workspace take up (i.e. a sum of the third column of "whos")
function memorydisp(varargin)
if isempty(varargin)
    disp('Execute this:    W = whos; memorydisp(W)')
elseif length(varargin) == 1
    if isstruct(varargin{1})
        W = varargin{1};
        BytesInMemory = 0;
        for i = 1:length(W)
            BytesInMemory = BytesInMemory + W(i).bytes;
        end
        if BytesInMemory <1000
            disp(['Workspace variables take up ',num2str(BytesInMemory),' bytes of memory.'])
        elseif BytesInMemory >= 1000 && BytesInMemory <10^6
            disp(['Workspace variables take up ',num2str(BytesInMemory),' bytes of memory = ',num2str(BytesInMemory/1000),' kB of memory.'])
        elseif BytesInMemory >= 10^6 && BytesInMemory <10^9
            disp(['Workspace variables take up ',num2str(BytesInMemory),' bytes of memory = ',num2str(BytesInMemory/(10^6)),' MB of memory.'])
        else
            disp(['Workspace variables take up ',num2str(BytesInMemory),' bytes of memory = ',num2str(BytesInMemory/(10^9)),' GB of memory.'])
        end
    else
        error('The input for memorydisp must be a "struct" generated by running "whos".')
    end
else
    error('memorydisp only accepts 0 or 1 argument')
end
end
